CREATE TABLE IF NOT EXISTS `cinemas` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, PRIMARY KEY(`id`))
CREATE TABLE IF NOT EXISTS `zones` (`id` TEXT NOT NULL, `cinemaId` TEXT NOT NULL, `name` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`cinemaId`) REFERENCES `cinemas`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )
CREATE INDEX IF NOT EXISTS `index_zones_cinemaId` ON `zones` (`cinemaId`)
CREATE TABLE IF NOT EXISTS `assets` (`id` TEXT NOT NULL, `zoneId` TEXT NOT NULL, `name` TEXT NOT NULL, `authorized` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`zoneId`) REFERENCES `zones`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )
CREATE INDEX IF NOT EXISTS `index_assets_zoneId` ON `assets` (`zoneId`)
CREATE TABLE IF NOT EXISTS `bindings` (`id` TEXT NOT NULL, `assetId` TEXT NOT NULL, `radio` TEXT NOT NULL, `address` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`assetId`) REFERENCES `assets`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )
CREATE INDEX IF NOT EXISTS `index_bindings_assetId` ON `bindings` (`assetId`)
CREATE UNIQUE INDEX IF NOT EXISTS `index_bindings_radio_address` ON `bindings` (`radio`, `address`)
CREATE TABLE IF NOT EXISTS `sessions` (`id` TEXT NOT NULL, `zoneId` TEXT NOT NULL, `mode` TEXT NOT NULL, `startMs` INTEGER NOT NULL, `endMs` INTEGER NOT NULL, `durationSeconds` INTEGER NOT NULL, `wifiCount` INTEGER NOT NULL, `bleCount` INTEGER NOT NULL, `assetCount` INTEGER NOT NULL, `wifiBatches` INTEGER NOT NULL, `bleEvents` INTEGER NOT NULL, `discarded` INTEGER NOT NULL, `dropped` INTEGER NOT NULL, `wifiHealthy` INTEGER NOT NULL, `bleHealthy` INTEGER NOT NULL, `demo` INTEGER NOT NULL, `planned` INTEGER, `actual` INTEGER, `gate` INTEGER, `point` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`zoneId`) REFERENCES `zones`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )
CREATE INDEX IF NOT EXISTS `index_sessions_zoneId` ON `sessions` (`zoneId`)
CREATE TABLE IF NOT EXISTS `results` (`sessionId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `at` INTEGER NOT NULL, `status` TEXT NOT NULL, `medianRssi` INTEGER, `spread` INTEGER NOT NULL, `consecutiveMisses` INTEGER NOT NULL, `baselineRssi` INTEGER, PRIMARY KEY(`sessionId`, `assetId`), FOREIGN KEY(`sessionId`) REFERENCES `sessions`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`assetId`) REFERENCES `assets`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )
CREATE INDEX IF NOT EXISTS `index_results_sessionId` ON `results` (`sessionId`)
CREATE INDEX IF NOT EXISTS `index_results_assetId` ON `results` (`assetId`)
CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)
INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, 'fa98c7a0db3d5734527b57307145c817')
